title: Barun Singh # your name (or website title) here
logo: "/IMG_20191230_142109.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
 Senior Software Engineer
  <br><br>
  <a href="mailto:barun.singh1204@gmail.com">barun.singh1204@gmail.com</a>
  <br><br>
  <a href="https://www.linkedin.com/in/barun-singh-1204/">LinkedIn Profile</a>  
theme: jekyll-theme-minimal
